#pragma once

#include <stdint.h>

#define MAIN_MENU_UI_SPRITE_COUNT  9

typedef enum {
    MAIN_MENU_UI_SPRITE_UI3DS_MENU = 0,
    MAIN_MENU_UI_SPRITE_BAG_MENU = 1,
    MAIN_MENU_UI_SPRITE_BALL_MENU = 2,
    MAIN_MENU_UI_SPRITE_DEX_MENU = 3,
    MAIN_MENU_UI_SPRITE_MENU_BORDER = 4,
    MAIN_MENU_UI_SPRITE_POKEMON_LEFT = 5,
    MAIN_MENU_UI_SPRITE_POKEMON_RIGHT = 6,
    MAIN_MENU_UI_SPRITE_SAVE_MENU = 7,
    MAIN_MENU_UI_SPRITE_TRAINER_CARD_MENU = 8,
} MainMenuUiSpriteId;

#define MAIN_MENU_UI_UI3DS_MENU_WIDTH  61
#define MAIN_MENU_UI_UI3DS_MENU_HEIGHT 54
extern const unsigned short ui3dsMenuSprite[MAIN_MENU_UI_UI3DS_MENU_WIDTH * MAIN_MENU_UI_UI3DS_MENU_HEIGHT];

#define MAIN_MENU_UI_BAG_MENU_WIDTH  61
#define MAIN_MENU_UI_BAG_MENU_HEIGHT 54
extern const unsigned short bagMenuSprite[MAIN_MENU_UI_BAG_MENU_WIDTH * MAIN_MENU_UI_BAG_MENU_HEIGHT];

#define MAIN_MENU_UI_BALL_MENU_WIDTH  61
#define MAIN_MENU_UI_BALL_MENU_HEIGHT 54
extern const unsigned short ballMenuSprite[MAIN_MENU_UI_BALL_MENU_WIDTH * MAIN_MENU_UI_BALL_MENU_HEIGHT];

#define MAIN_MENU_UI_DEX_MENU_WIDTH  61
#define MAIN_MENU_UI_DEX_MENU_HEIGHT 54
extern const unsigned short dexMenuSprite[MAIN_MENU_UI_DEX_MENU_WIDTH * MAIN_MENU_UI_DEX_MENU_HEIGHT];

#define MAIN_MENU_UI_MENU_BORDER_WIDTH  320
#define MAIN_MENU_UI_MENU_BORDER_HEIGHT 240
extern const unsigned short menuBorderSprite[MAIN_MENU_UI_MENU_BORDER_WIDTH * MAIN_MENU_UI_MENU_BORDER_HEIGHT];

#define MAIN_MENU_UI_POKEMON_LEFT_WIDTH  89
#define MAIN_MENU_UI_POKEMON_LEFT_HEIGHT 84
extern const unsigned short pokemonLeftSprite[MAIN_MENU_UI_POKEMON_LEFT_WIDTH * MAIN_MENU_UI_POKEMON_LEFT_HEIGHT];

#define MAIN_MENU_UI_POKEMON_RIGHT_WIDTH  89
#define MAIN_MENU_UI_POKEMON_RIGHT_HEIGHT 84
extern const unsigned short pokemonRightSprite[MAIN_MENU_UI_POKEMON_RIGHT_WIDTH * MAIN_MENU_UI_POKEMON_RIGHT_HEIGHT];

#define MAIN_MENU_UI_SAVE_MENU_WIDTH  61
#define MAIN_MENU_UI_SAVE_MENU_HEIGHT 54
extern const unsigned short saveMenuSprite[MAIN_MENU_UI_SAVE_MENU_WIDTH * MAIN_MENU_UI_SAVE_MENU_HEIGHT];

#define MAIN_MENU_UI_TRAINER_CARD_MENU_WIDTH  61
#define MAIN_MENU_UI_TRAINER_CARD_MENU_HEIGHT 54
extern const unsigned short trainerCardMenuSprite[MAIN_MENU_UI_TRAINER_CARD_MENU_WIDTH * MAIN_MENU_UI_TRAINER_CARD_MENU_HEIGHT];

extern const unsigned short* const mainMenuUiSprites[MAIN_MENU_UI_SPRITE_COUNT];
extern const uint16_t mainMenuUiSpritesWidths[MAIN_MENU_UI_SPRITE_COUNT];
extern const uint16_t mainMenuUiSpritesHeights[MAIN_MENU_UI_SPRITE_COUNT];
