#pragma once

#include <stdint.h>

#define MAIN_MENU_UI_SPRITE_COUNT  11

typedef enum {
    MAIN_MENU_UI_SPRITE_UI3DS_MENU = 0,
    MAIN_MENU_UI_SPRITE_BACKDROP_MENU = 1,
    MAIN_MENU_UI_SPRITE_BAG_MENU = 2,
    MAIN_MENU_UI_SPRITE_BALL_MENU = 3,
    MAIN_MENU_UI_SPRITE_DEX_MENU = 4,
    MAIN_MENU_UI_SPRITE_FRONT_FACING_MC = 5,
    MAIN_MENU_UI_SPRITE_MENU_BORDER = 6,
    MAIN_MENU_UI_SPRITE_POKEMON_LEFT = 7,
    MAIN_MENU_UI_SPRITE_POKEMON_RIGHT = 8,
    MAIN_MENU_UI_SPRITE_SAVE_MENU = 9,
    MAIN_MENU_UI_SPRITE_TRAINER_CARD_MENU = 10,
} MainMenuUiSpriteId;

#define MAIN_MENU_UI_UI3DS_MENU_WIDTH  61
#define MAIN_MENU_UI_UI3DS_MENU_HEIGHT 54
extern const unsigned short mainMenuUiUi3dsMenuSprite[MAIN_MENU_UI_UI3DS_MENU_WIDTH * MAIN_MENU_UI_UI3DS_MENU_HEIGHT];

#define MAIN_MENU_UI_BACKDROP_MENU_WIDTH  320
#define MAIN_MENU_UI_BACKDROP_MENU_HEIGHT 240
extern const unsigned short mainMenuUiBackdropMenuSprite[MAIN_MENU_UI_BACKDROP_MENU_WIDTH * MAIN_MENU_UI_BACKDROP_MENU_HEIGHT];

#define MAIN_MENU_UI_BAG_MENU_WIDTH  61
#define MAIN_MENU_UI_BAG_MENU_HEIGHT 54
extern const unsigned short mainMenuUiBagMenuSprite[MAIN_MENU_UI_BAG_MENU_WIDTH * MAIN_MENU_UI_BAG_MENU_HEIGHT];

#define MAIN_MENU_UI_BALL_MENU_WIDTH  61
#define MAIN_MENU_UI_BALL_MENU_HEIGHT 54
extern const unsigned short mainMenuUiBallMenuSprite[MAIN_MENU_UI_BALL_MENU_WIDTH * MAIN_MENU_UI_BALL_MENU_HEIGHT];

#define MAIN_MENU_UI_DEX_MENU_WIDTH  61
#define MAIN_MENU_UI_DEX_MENU_HEIGHT 54
extern const unsigned short mainMenuUiDexMenuSprite[MAIN_MENU_UI_DEX_MENU_WIDTH * MAIN_MENU_UI_DEX_MENU_HEIGHT];

#define MAIN_MENU_UI_FRONT_FACING_MC_WIDTH  64
#define MAIN_MENU_UI_FRONT_FACING_MC_HEIGHT 64
extern const unsigned short mainMenuUiFrontFacingMcSprite[MAIN_MENU_UI_FRONT_FACING_MC_WIDTH * MAIN_MENU_UI_FRONT_FACING_MC_HEIGHT];

#define MAIN_MENU_UI_MENU_BORDER_WIDTH  320
#define MAIN_MENU_UI_MENU_BORDER_HEIGHT 240
extern const unsigned short mainMenuUiMenuBorderSprite[MAIN_MENU_UI_MENU_BORDER_WIDTH * MAIN_MENU_UI_MENU_BORDER_HEIGHT];

#define MAIN_MENU_UI_POKEMON_LEFT_WIDTH  89
#define MAIN_MENU_UI_POKEMON_LEFT_HEIGHT 84
extern const unsigned short mainMenuUiPokemonLeftSprite[MAIN_MENU_UI_POKEMON_LEFT_WIDTH * MAIN_MENU_UI_POKEMON_LEFT_HEIGHT];

#define MAIN_MENU_UI_POKEMON_RIGHT_WIDTH  89
#define MAIN_MENU_UI_POKEMON_RIGHT_HEIGHT 84
extern const unsigned short mainMenuUiPokemonRightSprite[MAIN_MENU_UI_POKEMON_RIGHT_WIDTH * MAIN_MENU_UI_POKEMON_RIGHT_HEIGHT];

#define MAIN_MENU_UI_SAVE_MENU_WIDTH  61
#define MAIN_MENU_UI_SAVE_MENU_HEIGHT 54
extern const unsigned short mainMenuUiSaveMenuSprite[MAIN_MENU_UI_SAVE_MENU_WIDTH * MAIN_MENU_UI_SAVE_MENU_HEIGHT];

#define MAIN_MENU_UI_TRAINER_CARD_MENU_WIDTH  61
#define MAIN_MENU_UI_TRAINER_CARD_MENU_HEIGHT 54
extern const unsigned short mainMenuUiTrainerCardMenuSprite[MAIN_MENU_UI_TRAINER_CARD_MENU_WIDTH * MAIN_MENU_UI_TRAINER_CARD_MENU_HEIGHT];

extern const unsigned short* const mainMenuUiSprites[MAIN_MENU_UI_SPRITE_COUNT];
extern const uint16_t mainMenuUiSpritesWidths[MAIN_MENU_UI_SPRITE_COUNT];
extern const uint16_t mainMenuUiSpritesHeights[MAIN_MENU_UI_SPRITE_COUNT];
