#pragma once

#define BATTLE_BAG_ITEM_DESCRIPTION_WIDTH  252
#define BATTLE_BAG_ITEM_DESCRIPTION_HEIGHT 70

extern const unsigned short itemDescription[BATTLE_BAG_ITEM_DESCRIPTION_WIDTH * BATTLE_BAG_ITEM_DESCRIPTION_HEIGHT];
