#pragma once

#include <stdint.h>

#define POKEDEX_TYPE_SPRITE_COUNT  18

typedef enum {
    POKEDEX_TYPE_SPRITE_BUG = 0,
    POKEDEX_TYPE_SPRITE_DARK = 1,
    POKEDEX_TYPE_SPRITE_DRAGON = 2,
    POKEDEX_TYPE_SPRITE_ELECTRIC = 3,
    POKEDEX_TYPE_SPRITE_FAIRY = 4,
    POKEDEX_TYPE_SPRITE_FIGHTING = 5,
    POKEDEX_TYPE_SPRITE_FIRE = 6,
    POKEDEX_TYPE_SPRITE_FLYING = 7,
    POKEDEX_TYPE_SPRITE_GHOST = 8,
    POKEDEX_TYPE_SPRITE_GRASS = 9,
    POKEDEX_TYPE_SPRITE_GROUND = 10,
    POKEDEX_TYPE_SPRITE_ICE = 11,
    POKEDEX_TYPE_SPRITE_NORMAL = 12,
    POKEDEX_TYPE_SPRITE_POISON = 13,
    POKEDEX_TYPE_SPRITE_PSY = 14,
    POKEDEX_TYPE_SPRITE_ROCK = 15,
    POKEDEX_TYPE_SPRITE_STEEL = 16,
    POKEDEX_TYPE_SPRITE_WATER = 17,
} PokedexTypeSpriteId;

#define POKEDEX_TYPE_BUG_WIDTH  64
#define POKEDEX_TYPE_BUG_HEIGHT 24
extern const unsigned short pokedexTypeBugSprite[POKEDEX_TYPE_BUG_WIDTH * POKEDEX_TYPE_BUG_HEIGHT];

#define POKEDEX_TYPE_DARK_WIDTH  64
#define POKEDEX_TYPE_DARK_HEIGHT 24
extern const unsigned short pokedexTypeDarkSprite[POKEDEX_TYPE_DARK_WIDTH * POKEDEX_TYPE_DARK_HEIGHT];

#define POKEDEX_TYPE_DRAGON_WIDTH  64
#define POKEDEX_TYPE_DRAGON_HEIGHT 24
extern const unsigned short pokedexTypeDragonSprite[POKEDEX_TYPE_DRAGON_WIDTH * POKEDEX_TYPE_DRAGON_HEIGHT];

#define POKEDEX_TYPE_ELECTRIC_WIDTH  64
#define POKEDEX_TYPE_ELECTRIC_HEIGHT 24
extern const unsigned short pokedexTypeElectricSprite[POKEDEX_TYPE_ELECTRIC_WIDTH * POKEDEX_TYPE_ELECTRIC_HEIGHT];

#define POKEDEX_TYPE_FAIRY_WIDTH  64
#define POKEDEX_TYPE_FAIRY_HEIGHT 24
extern const unsigned short pokedexTypeFairySprite[POKEDEX_TYPE_FAIRY_WIDTH * POKEDEX_TYPE_FAIRY_HEIGHT];

#define POKEDEX_TYPE_FIGHTING_WIDTH  64
#define POKEDEX_TYPE_FIGHTING_HEIGHT 24
extern const unsigned short pokedexTypeFightingSprite[POKEDEX_TYPE_FIGHTING_WIDTH * POKEDEX_TYPE_FIGHTING_HEIGHT];

#define POKEDEX_TYPE_FIRE_WIDTH  64
#define POKEDEX_TYPE_FIRE_HEIGHT 24
extern const unsigned short pokedexTypeFireSprite[POKEDEX_TYPE_FIRE_WIDTH * POKEDEX_TYPE_FIRE_HEIGHT];

#define POKEDEX_TYPE_FLYING_WIDTH  64
#define POKEDEX_TYPE_FLYING_HEIGHT 24
extern const unsigned short pokedexTypeFlyingSprite[POKEDEX_TYPE_FLYING_WIDTH * POKEDEX_TYPE_FLYING_HEIGHT];

#define POKEDEX_TYPE_GHOST_WIDTH  64
#define POKEDEX_TYPE_GHOST_HEIGHT 24
extern const unsigned short pokedexTypeGhostSprite[POKEDEX_TYPE_GHOST_WIDTH * POKEDEX_TYPE_GHOST_HEIGHT];

#define POKEDEX_TYPE_GRASS_WIDTH  64
#define POKEDEX_TYPE_GRASS_HEIGHT 24
extern const unsigned short pokedexTypeGrassSprite[POKEDEX_TYPE_GRASS_WIDTH * POKEDEX_TYPE_GRASS_HEIGHT];

#define POKEDEX_TYPE_GROUND_WIDTH  64
#define POKEDEX_TYPE_GROUND_HEIGHT 24
extern const unsigned short pokedexTypeGroundSprite[POKEDEX_TYPE_GROUND_WIDTH * POKEDEX_TYPE_GROUND_HEIGHT];

#define POKEDEX_TYPE_ICE_WIDTH  64
#define POKEDEX_TYPE_ICE_HEIGHT 24
extern const unsigned short pokedexTypeIceSprite[POKEDEX_TYPE_ICE_WIDTH * POKEDEX_TYPE_ICE_HEIGHT];

#define POKEDEX_TYPE_NORMAL_WIDTH  64
#define POKEDEX_TYPE_NORMAL_HEIGHT 24
extern const unsigned short pokedexTypeNormalSprite[POKEDEX_TYPE_NORMAL_WIDTH * POKEDEX_TYPE_NORMAL_HEIGHT];

#define POKEDEX_TYPE_POISON_WIDTH  64
#define POKEDEX_TYPE_POISON_HEIGHT 24
extern const unsigned short pokedexTypePoisonSprite[POKEDEX_TYPE_POISON_WIDTH * POKEDEX_TYPE_POISON_HEIGHT];

#define POKEDEX_TYPE_PSY_WIDTH  64
#define POKEDEX_TYPE_PSY_HEIGHT 24
extern const unsigned short pokedexTypePsySprite[POKEDEX_TYPE_PSY_WIDTH * POKEDEX_TYPE_PSY_HEIGHT];

#define POKEDEX_TYPE_ROCK_WIDTH  64
#define POKEDEX_TYPE_ROCK_HEIGHT 24
extern const unsigned short pokedexTypeRockSprite[POKEDEX_TYPE_ROCK_WIDTH * POKEDEX_TYPE_ROCK_HEIGHT];

#define POKEDEX_TYPE_STEEL_WIDTH  64
#define POKEDEX_TYPE_STEEL_HEIGHT 24
extern const unsigned short pokedexTypeSteelSprite[POKEDEX_TYPE_STEEL_WIDTH * POKEDEX_TYPE_STEEL_HEIGHT];

#define POKEDEX_TYPE_WATER_WIDTH  64
#define POKEDEX_TYPE_WATER_HEIGHT 24
extern const unsigned short pokedexTypeWaterSprite[POKEDEX_TYPE_WATER_WIDTH * POKEDEX_TYPE_WATER_HEIGHT];

extern const unsigned short* const pokedexTypesSprites[POKEDEX_TYPE_SPRITE_COUNT];
extern const uint16_t pokedexTypesSpritesWidths[POKEDEX_TYPE_SPRITE_COUNT];
extern const uint16_t pokedexTypesSpritesHeights[POKEDEX_TYPE_SPRITE_COUNT];
