#ifndef PREDEFINED_GRAPHICS_H
#define PREDEFINED_GRAPHICS_H

#include "graphics.h"

// Tile IDs for map
typedef enum {
    TILE_GRASS = 0,
    TILE_BLACK,
    TILE_TREE_TOP,
    TILE_TREE_BOTTOM,
    TILE_GRASS_PATCH,
    TILE_POKEMON_CENTER_TOP_LEFT,
    TILE_POKEMON_CENTER_TOP_MIDDLE,
    TILE_POKEMON_CENTER_TOP_RIGHT,
    TILE_POKEMON_CENTER_MIDDLE_LEFT,
    TILE_POKEMON_CENTER_MIDDLE_MIDDLE,
    TILE_POKEMON_CENTER_MIDDLE_RIGHT,
    TILE_POKEMON_CENTER_BOTTOM_LEFT,
    TILE_POKEMON_CENTER_BOTTOM_MIDDLE,
    TILE_POKEMON_CENTER_BOTTOM_RIGHT,
    TILE_POKE_MART_TOP_LEFT,
    TILE_POKE_MART_TOP_MIDDLE,
    TILE_POKE_MART_TOP_RIGHT,
    TILE_POKE_MART_MIDDLE_LEFT,
    TILE_POKE_MART_MIDDLE_MIDDLE,
    TILE_POKE_MART_MIDDLE_RIGHT,
    TILE_POKE_MART_BOTTOM_LEFT,
    TILE_POKE_MART_BOTTOM_MIDDLE,
    TILE_POKE_MART_BOTTOM_RIGHT,
    TILE_HOUSE_TOP_LEFT,
    TILE_HOUSE_TOP_MIDDLE,
    TILE_HOUSE_TOP_RIGHT,
    TILE_HOUSE_MIDDLE_LEFT,
    TILE_HOUSE_MIDDLE_MIDDLE,
    TILE_HOUSE_MIDDLE_RIGHT,
    TILE_HOUSE_BOTTOM_LEFT,
    TILE_HOUSE_BOTTOM_MIDDLE,
    TILE_HOUSE_BOTTOM_RIGHT,
    TILE_GYM_TOP_LEFT,
    TILE_GYM_TOP_MIDDLE,
    TILE_GYM_TOP_RIGHT,
    TILE_GYM_MIDDLE_LEFT,
    TILE_GYM_MIDDLE_MIDDLE,
    TILE_GYM_MIDDLE_RIGHT,
    TILE_GYM_BOTTOM_LEFT,
    TILE_GYM_BOTTOM_MIDDLE,
    TILE_GYM_BOTTOM_RIGHT,
    TILE_CLIFF_LEFT,
    TILE_CLIFF_MIDDLE,
    TILE_CLIFF_RIGHT,
    TILE_BACKDROP1_START,
    TILE_BACKDROP1_END = TILE_BACKDROP1_START + 299,
    TILE_GROUND_START,
    TILE_GROUND_END = TILE_GROUND_START + 299,
    TILE_POKEMON_CENTER_INTERIOR_START,
    TILE_POKEMON_CENTER_INTERIOR_END = TILE_POKEMON_CENTER_INTERIOR_START + 299,
    TILE_POKE_MART_INTERIOR_START,
    TILE_POKE_MART_INTERIOR_END = TILE_POKE_MART_INTERIOR_START + 299,
    TILE_HOUSE_INTERIOR_START,
    TILE_HOUSE_INTERIOR_END = TILE_HOUSE_INTERIOR_START + 299,
    TILE_GYM_INTERIOR_START,
    TILE_GYM_INTERIOR_END = TILE_GYM_INTERIOR_START + 299,
    TILE_COUNT = TILE_GYM_INTERIOR_END + 1,
} TileId;

// 16x16 tiles 
extern short tiles[TILE_COUNT][TILE_SIZE * TILE_SIZE];


void init_predefined_graphics(void);


#endif
