#include "budewSprite.c"
#include "charizardSprite.c"
#include "charmanderSprite.c"
#include "charmeleonSprite.c"
#include "feebasSprite.c"
#include "gabiteSprite.c"
#include "garchompSprite.c"
#include "gibleSprite.c"
#include "lucarioSprite.c"
#include "miloticSprite.c"
#include "rayquazaSprite.c"
#include "rioluSprite.c"
#include "roseradeSprite.c"
#include "spiritombSprite.c"
#include "togekissSprite.c"
#include "togepiSprite.c"
#include "togeticSprite.c"

