#pragma once

#include <stdint.h>

#define NEW_POKEMART_IDEA_SPRITE_COUNT  2

typedef enum {
    NEW_POKEMART_IDEA_SPRITE_POKE_BUILDING = 0,
    NEW_POKEMART_IDEA_SPRITE_POKE_BUILDING_INTERIOR = 1,
} NewPokemartIdeaSpriteId;

#define NEW_POKEMART_IDEA_POKE_BUILDING_WIDTH  160
#define NEW_POKEMART_IDEA_POKE_BUILDING_HEIGHT 152
extern const unsigned short pokeBuildingSprite[NEW_POKEMART_IDEA_POKE_BUILDING_WIDTH * NEW_POKEMART_IDEA_POKE_BUILDING_HEIGHT];

#define NEW_POKEMART_IDEA_POKE_BUILDING_INTERIOR_WIDTH  320
#define NEW_POKEMART_IDEA_POKE_BUILDING_INTERIOR_HEIGHT 240
extern const unsigned short pokeBuildingInteriorSprite[NEW_POKEMART_IDEA_POKE_BUILDING_INTERIOR_WIDTH * NEW_POKEMART_IDEA_POKE_BUILDING_INTERIOR_HEIGHT];

extern const unsigned short* const newPokemartIdeaSprites[NEW_POKEMART_IDEA_SPRITE_COUNT];
extern const uint16_t newPokemartIdeaSpritesWidths[NEW_POKEMART_IDEA_SPRITE_COUNT];
extern const uint16_t newPokemartIdeaSpritesHeights[NEW_POKEMART_IDEA_SPRITE_COUNT];
