#pragma once

#define MC_WALKING_SOUTH_EAST_TILE_SIZE 36
#define MC_WALKING_SOUTH_EAST_FRAME_COUNT 8

extern const unsigned short mcWalkingSouthEast_frame_0[MC_WALKING_SOUTH_EAST_TILE_SIZE * MC_WALKING_SOUTH_EAST_TILE_SIZE];
extern const unsigned short mcWalkingSouthEast_frame_1[MC_WALKING_SOUTH_EAST_TILE_SIZE * MC_WALKING_SOUTH_EAST_TILE_SIZE];
extern const unsigned short mcWalkingSouthEast_frame_2[MC_WALKING_SOUTH_EAST_TILE_SIZE * MC_WALKING_SOUTH_EAST_TILE_SIZE];
extern const unsigned short mcWalkingSouthEast_frame_3[MC_WALKING_SOUTH_EAST_TILE_SIZE * MC_WALKING_SOUTH_EAST_TILE_SIZE];
extern const unsigned short mcWalkingSouthEast_frame_4[MC_WALKING_SOUTH_EAST_TILE_SIZE * MC_WALKING_SOUTH_EAST_TILE_SIZE];
extern const unsigned short mcWalkingSouthEast_frame_5[MC_WALKING_SOUTH_EAST_TILE_SIZE * MC_WALKING_SOUTH_EAST_TILE_SIZE];
extern const unsigned short mcWalkingSouthEast_frame_6[MC_WALKING_SOUTH_EAST_TILE_SIZE * MC_WALKING_SOUTH_EAST_TILE_SIZE];
extern const unsigned short mcWalkingSouthEast_frame_7[MC_WALKING_SOUTH_EAST_TILE_SIZE * MC_WALKING_SOUTH_EAST_TILE_SIZE];

extern const unsigned short* const mcWalkingSouthEastFrames[MC_WALKING_SOUTH_EAST_FRAME_COUNT];
