#pragma once

#define MC_WALKING_NORTH_WEST_TILE_SIZE 36
#define MC_WALKING_NORTH_WEST_FRAME_COUNT 8

extern const unsigned short mcWalkingNorthWest_frame_0[MC_WALKING_NORTH_WEST_TILE_SIZE * MC_WALKING_NORTH_WEST_TILE_SIZE];
extern const unsigned short mcWalkingNorthWest_frame_1[MC_WALKING_NORTH_WEST_TILE_SIZE * MC_WALKING_NORTH_WEST_TILE_SIZE];
extern const unsigned short mcWalkingNorthWest_frame_2[MC_WALKING_NORTH_WEST_TILE_SIZE * MC_WALKING_NORTH_WEST_TILE_SIZE];
extern const unsigned short mcWalkingNorthWest_frame_3[MC_WALKING_NORTH_WEST_TILE_SIZE * MC_WALKING_NORTH_WEST_TILE_SIZE];
extern const unsigned short mcWalkingNorthWest_frame_4[MC_WALKING_NORTH_WEST_TILE_SIZE * MC_WALKING_NORTH_WEST_TILE_SIZE];
extern const unsigned short mcWalkingNorthWest_frame_5[MC_WALKING_NORTH_WEST_TILE_SIZE * MC_WALKING_NORTH_WEST_TILE_SIZE];
extern const unsigned short mcWalkingNorthWest_frame_6[MC_WALKING_NORTH_WEST_TILE_SIZE * MC_WALKING_NORTH_WEST_TILE_SIZE];
extern const unsigned short mcWalkingNorthWest_frame_7[MC_WALKING_NORTH_WEST_TILE_SIZE * MC_WALKING_NORTH_WEST_TILE_SIZE];

extern const unsigned short* const mcWalkingNorthWestFrames[MC_WALKING_NORTH_WEST_FRAME_COUNT];
