#ifndef GAME_CONSTANTS_H
#define GAME_CONSTANTS_H

#define LIGHT_GREEN 0x9772

#define SCREEN_WIDTH  320
#define SCREEN_HEIGHT 240
#define NUM_TILES_X (SCREEN_WIDTH / TILE_SIZE)
#define NUM_TILES_Y (SCREEN_HEIGHT / TILE_SIZE)

#define TEXTBOX_X 0
#define TEXTBOX_Y (SCREEN_HEIGHT - TEXT_BOX_HEIGHT)

#define SPACEBAR_SPEED_FRAMES 8

#define TITLE_TEXT_X 10
#define TITLE_TEXT_Y 10

#endif
