#pragma once

#define POKEMART_BUY_SCREEN_SPRITE_WIDTH  320
#define POKEMART_BUY_SCREEN_SPRITE_HEIGHT 240

extern const unsigned short pokemartBuyScreenSprite[POKEMART_BUY_SCREEN_SPRITE_WIDTH * POKEMART_BUY_SCREEN_SPRITE_HEIGHT];
