#pragma once

#define POKEMART_SELECT_CURSOR_SPRITE_WIDTH  166
#define POKEMART_SELECT_CURSOR_SPRITE_HEIGHT 21

extern const unsigned short pokemartSelectCursorSprite[POKEMART_SELECT_CURSOR_SPRITE_WIDTH * POKEMART_SELECT_CURSOR_SPRITE_HEIGHT];
