#pragma once

#define POKEMART_SELECT_CURSOR_SPRITE_WIDTH  166
#define POKEMART_SELECT_CURSOR_SPRITE_HEIGHT 21

extern const unsigned short pokemartSelectCursorSprite[POKEMART_SELECT_CURSOR_SPRITE_WIDTH * POKEMART_SELECT_CURSOR_SPRITE_HEIGHT];

#define POKEMART_BUY_SCREEN_SPRITE_WIDTH  320
#define POKEMART_BUY_SCREEN_SPRITE_HEIGHT 240

extern const unsigned short pokemartBuyScreenSprite[POKEMART_BUY_SCREEN_SPRITE_WIDTH * POKEMART_BUY_SCREEN_SPRITE_HEIGHT];
