#pragma once

// Auto-generated by ImageConvertHelpers/convertBattleIconsToC.py

#define BATTLE_ICON_SMALL_WIDTH  57
#define BATTLE_ICON_SMALL_HEIGHT 33
#define BATTLE_ICON_FIGHT_WIDTH  102
#define BATTLE_ICON_FIGHT_HEIGHT 74

extern const unsigned short battleIconRun[BATTLE_ICON_SMALL_WIDTH * BATTLE_ICON_SMALL_HEIGHT];
extern const unsigned short battleIconBag[BATTLE_ICON_SMALL_WIDTH * BATTLE_ICON_SMALL_HEIGHT];
extern const unsigned short battleIconFight[BATTLE_ICON_FIGHT_WIDTH * BATTLE_ICON_FIGHT_HEIGHT];

