#pragma once

#include <stdint.h>

#define POKEDEX_MENU_SPRITE_COUNT  14

typedef enum {
    POKEDEX_MENU_SPRITE_BOTTOM = 0,
    POKEDEX_MENU_SPRITE_CAUGHT = 1,
    POKEDEX_MENU_SPRITE_CAUGHT_SELECTED = 2,
    POKEDEX_MENU_SPRITE_DESCRIPTION = 3,
    POKEDEX_MENU_SPRITE_DOWN_ARROW = 4,
    POKEDEX_MENU_SPRITE_INFO = 5,
    POKEDEX_MENU_SPRITE_LIST = 6,
    POKEDEX_MENU_SPRITE_SELECT = 7,
    POKEDEX_MENU_SPRITE_SUMMARY = 8,
    POKEDEX_MENU_SPRITE_UP_ARROW = 9,
    POKEDEX_MENU_SPRITE_X = 10,
    POKEDEX_MENU_SPRITE_SCROLL_MENU = 11,
    POKEDEX_MENU_SPRITE_POKEMON = 12,
    POKEDEX_MENU_SPRITE_POKEMON_SELECTED_POKEDEX = 13,
} PokedexMenuSpriteId;

#define POKEDEX_MENU_BOTTOM_WIDTH  340
#define POKEDEX_MENU_BOTTOM_HEIGHT 240
extern const unsigned short pokedexBottomSprite[POKEDEX_MENU_BOTTOM_WIDTH * POKEDEX_MENU_BOTTOM_HEIGHT];

#define POKEDEX_MENU_CAUGHT_WIDTH  26
#define POKEDEX_MENU_CAUGHT_HEIGHT 26
extern const unsigned short pokedexCaughtSprite[POKEDEX_MENU_CAUGHT_WIDTH * POKEDEX_MENU_CAUGHT_HEIGHT];

#define POKEDEX_MENU_CAUGHT_SELECTED_WIDTH  26
#define POKEDEX_MENU_CAUGHT_SELECTED_HEIGHT 26
extern const unsigned short pokedexCaughtSelectedSprite[POKEDEX_MENU_CAUGHT_SELECTED_WIDTH * POKEDEX_MENU_CAUGHT_SELECTED_HEIGHT];

#define POKEDEX_MENU_DESCRIPTION_WIDTH  320
#define POKEDEX_MENU_DESCRIPTION_HEIGHT 240
extern const unsigned short pokedexDescriptionSprite[POKEDEX_MENU_DESCRIPTION_WIDTH * POKEDEX_MENU_DESCRIPTION_HEIGHT];

#define POKEDEX_MENU_DOWN_ARROW_WIDTH  28
#define POKEDEX_MENU_DOWN_ARROW_HEIGHT 34
extern const unsigned short pokedexDownArrowSprite[POKEDEX_MENU_DOWN_ARROW_WIDTH * POKEDEX_MENU_DOWN_ARROW_HEIGHT];

#define POKEDEX_MENU_INFO_WIDTH  62
#define POKEDEX_MENU_INFO_HEIGHT 42
extern const unsigned short pokedexInfoSprite[POKEDEX_MENU_INFO_WIDTH * POKEDEX_MENU_INFO_HEIGHT];

#define POKEDEX_MENU_LIST_WIDTH  320
#define POKEDEX_MENU_LIST_HEIGHT 240
extern const unsigned short pokedexListSprite[POKEDEX_MENU_LIST_WIDTH * POKEDEX_MENU_LIST_HEIGHT];

#define POKEDEX_MENU_SELECT_WIDTH  113
#define POKEDEX_MENU_SELECT_HEIGHT 122
extern const unsigned short pokedexSelectSprite[POKEDEX_MENU_SELECT_WIDTH * POKEDEX_MENU_SELECT_HEIGHT];

#define POKEDEX_MENU_SUMMARY_WIDTH  320
#define POKEDEX_MENU_SUMMARY_HEIGHT 240
extern const unsigned short pokedexSummarySprite[POKEDEX_MENU_SUMMARY_WIDTH * POKEDEX_MENU_SUMMARY_HEIGHT];

#define POKEDEX_MENU_UP_ARROW_WIDTH  28
#define POKEDEX_MENU_UP_ARROW_HEIGHT 34
extern const unsigned short pokedexUpArrowSprite[POKEDEX_MENU_UP_ARROW_WIDTH * POKEDEX_MENU_UP_ARROW_HEIGHT];

#define POKEDEX_MENU_X_WIDTH  28
#define POKEDEX_MENU_X_HEIGHT 28
extern const unsigned short pokedexXSprite[POKEDEX_MENU_X_WIDTH * POKEDEX_MENU_X_HEIGHT];

#define POKEDEX_MENU_SCROLL_MENU_WIDTH  10
#define POKEDEX_MENU_SCROLL_MENU_HEIGHT 203
extern const unsigned short scrollMenuSprite[POKEDEX_MENU_SCROLL_MENU_WIDTH * POKEDEX_MENU_SCROLL_MENU_HEIGHT];

#define POKEDEX_MENU_POKEMON_WIDTH  320
#define POKEDEX_MENU_POKEMON_HEIGHT 240
extern const unsigned short pokedexPokemonSprite[POKEDEX_MENU_POKEMON_WIDTH * POKEDEX_MENU_POKEMON_HEIGHT];

#define POKEDEX_MENU_POKEMON_SELECTED_POKEDEX_WIDTH  320
#define POKEDEX_MENU_POKEMON_SELECTED_POKEDEX_HEIGHT 240
extern const unsigned short pokemonSelectedPokedexSprite[POKEDEX_MENU_POKEMON_SELECTED_POKEDEX_WIDTH * POKEDEX_MENU_POKEMON_SELECTED_POKEDEX_HEIGHT];

extern const unsigned short* const pokedexMenuSprites[POKEDEX_MENU_SPRITE_COUNT];
extern const uint16_t pokedexMenuSpritesWidths[POKEDEX_MENU_SPRITE_COUNT];
extern const uint16_t pokedexMenuSpritesHeights[POKEDEX_MENU_SPRITE_COUNT];
