#pragma once

#define TRAINER_CARD_BACK_SPRITE_WIDTH  320
#define TRAINER_CARD_BACK_SPRITE_HEIGHT 240

extern const unsigned short trainerCardBackSprite[TRAINER_CARD_BACK_SPRITE_WIDTH * TRAINER_CARD_BACK_SPRITE_HEIGHT];
